version: '3.8'

services:
  db-mysql:
    image: mysql:8.0
    container_name: mysql-matricula
    environment:
      MYSQL_ROOT_PASSWORD: '158575Z'
      MYSQL_DATABASE: 'SistemaMatricula_DB'
      
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p158575Z"]
      timeout: 5s
      retries: 10
      interval: 3s

  api-sistema:
    build:
      context: .
      dockerfile: SistemaDeMatricula/Percistencia/Docker/Dockerfile
    container_name: api-matricula
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-mysql;Port=3306;Database=SistemaMatricula_DB;Uid=root;Pwd=158575Z;
    depends_on:
      db-mysql:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:4-management
    container_name: escola_rabbitmq
    ports:
      - "5672:5672"   # Porta para o C# enviar/receber mensagens
      - "15672:15672" # Porta para você abrir o painel no navegador
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest      