@echo off
echo Deletando relatorios antigos...
if exist coveragereport rmdir /s /q coveragereport

echo Executando testes e coletando cobertura...
dotnet test --collect:"XPlat Code Coverage"

echo Gerando relatorio limpo (apenas codigo de producao)...
reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Html -assemblyfilters:"-*.Test*;-*.Shared*" -filefilters:"-*.g.cs;-*Migrations*"

echo Abrindo relatorio no navegador...
start coveragereport/index.html