// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeMatricula.Infraestrutura.Data;

#nullable disable

namespace SistemaDeMatricula.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623020803_AdicionarUsuarioId")]
    partial class AdicionarUsuarioId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Disciplina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int")
                        .HasColumnName("CargaHoraria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas", (string)null);
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Estudante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ComplexProperty<Dictionary<string, object>>("Cpf", "SistemaDeMatricula.Domain.Modelos.Estudante.Cpf#ObjectCPF", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DataNascimento", "SistemaDeMatricula.Domain.Modelos.Estudante.DataNascimento#ObjectDataNascimento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Valor")
                                .HasColumnType("date")
                                .HasColumnName("DataNascimento");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "SistemaDeMatricula.Domain.Modelos.Estudante.Email#ObjectEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NomeCompleto", "SistemaDeMatricula.Domain.Modelos.Estudante.NomeCompleto#ObjectNomeCompleto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("NomeCompleto");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Telefone", "SistemaDeMatricula.Domain.Modelos.Estudante.Telefone#ObjectTelefone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Telefone");
                        });

                    b.HasKey("Id");

                    b.ToTable("Estudantes", (string)null);
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EstudanteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.HasIndex("EstudanteId", "TurmaId")
                        .IsUnique();

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Importancia")
                        .HasColumnType("int");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("Categoria");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ComplexProperty<Dictionary<string, object>>("Cpf", "SistemaDeMatricula.Domain.Modelos.Professor.Cpf#ObjectCPF", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DataNascimento", "SistemaDeMatricula.Domain.Modelos.Professor.DataNascimento#ObjectDataNascimento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Valor")
                                .HasColumnType("date");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "SistemaDeMatricula.Domain.Modelos.Professor.Email#ObjectEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NomeCompleto", "SistemaDeMatricula.Domain.Modelos.Professor.NomeCompleto#ObjectNomeCompleto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("Nome");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Salario", "SistemaDeMatricula.Domain.Modelos.Professor.Salario#ValorMonetario", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Salario");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Telefone", "SistemaDeMatricula.Domain.Modelos.Professor.Telefone#ObjectTelefone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Telefone");
                        });

                    b.HasKey("Id");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("int");

                    b.Property<string>("CodigoTurma")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CodigoTurma");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Matricula", b =>
                {
                    b.HasOne("SistemaDeMatricula.Domain.Modelos.Estudante", "Estudante")
                        .WithMany("Matriculas")
                        .HasForeignKey("EstudanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeMatricula.Domain.Modelos.Turma", "Turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudante");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Nota", b =>
                {
                    b.HasOne("SistemaDeMatricula.Domain.Modelos.Matricula", "Matricula")
                        .WithMany("Notas")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Turma", b =>
                {
                    b.HasOne("SistemaDeMatricula.Domain.Modelos.Disciplina", "Disciplina")
                        .WithMany("Turmas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeMatricula.Domain.Modelos.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Disciplina", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Estudante", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Matricula", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SistemaDeMatricula.Domain.Modelos.Turma", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
