// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitemaDeMatricula.InfraEstrutura.Data;

#nullable disable

namespace SitemaDeMatricula.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411232957_PrimeiraMigracao")]
    partial class PrimeiraMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Disciplina", b =>
                {
                    b.Property<Guid>("DisciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DisciplinaId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Estudante", b =>
                {
                    b.Property<Guid>("EstudanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TurmaId")
                        .HasColumnType("char(36)");

                    b.ComplexProperty<Dictionary<string, object>>("Cpf", "SitemaDeMatricula.Domain.Modelos.Estudante.Cpf#ObjectCPF", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("DataNascimento", "SitemaDeMatricula.Domain.Modelos.Estudante.DataNascimento#ObjectDataNascimento", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Valor")
                                .HasColumnType("date")
                                .HasColumnName("DataNascimento");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "SitemaDeMatricula.Domain.Modelos.Estudante.Email#ObjectEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NomeCompleto", "SitemaDeMatricula.Domain.Modelos.Estudante.NomeCompleto#ObjectNomeCompleto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("NomeCompleto");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Telefone", "SitemaDeMatricula.Domain.Modelos.Estudante.Telefone#ObjectTelefone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Telefone");
                        });

                    b.HasKey("EstudanteId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Estudantes");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Matricula", b =>
                {
                    b.Property<Guid>("MatriculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EstudanteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("char(36)");

                    b.HasKey("MatriculaId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("EstudanteId", "TurmaId")
                        .IsUnique();

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Professor", b =>
                {
                    b.Property<Guid>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("Categoria");

                    b.ComplexProperty<Dictionary<string, object>>("Cpf", "SitemaDeMatricula.Domain.Modelos.Professor.Cpf#ObjectCPF", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "SitemaDeMatricula.Domain.Modelos.Professor.Email#ObjectEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Nome", "SitemaDeMatricula.Domain.Modelos.Professor.Nome#ObjectNomeCompleto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("Nome");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Salario", "SitemaDeMatricula.Domain.Modelos.Professor.Salario#ValorMonetario", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Salario");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Telefone", "SitemaDeMatricula.Domain.Modelos.Professor.Telefone#ObjectTelefone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Telefone");
                        });

                    b.HasKey("ProfessorId");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Turma", b =>
                {
                    b.Property<Guid>("TurmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoTurma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("char(36)");

                    b.HasKey("TurmaId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Estudante", b =>
                {
                    b.HasOne("SitemaDeMatricula.Domain.Modelos.Turma", null)
                        .WithMany("Estudantes")
                        .HasForeignKey("TurmaId");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Matricula", b =>
                {
                    b.HasOne("SitemaDeMatricula.Domain.Modelos.Estudante", "Estudante")
                        .WithMany("Matriculas")
                        .HasForeignKey("EstudanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SitemaDeMatricula.Domain.Modelos.Turma", "Turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudante");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Turma", b =>
                {
                    b.HasOne("SitemaDeMatricula.Domain.Modelos.Disciplina", "Disciplina")
                        .WithMany("Turmas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SitemaDeMatricula.Domain.Modelos.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Disciplina", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Estudante", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SitemaDeMatricula.Domain.Modelos.Turma", b =>
                {
                    b.Navigation("Estudantes");

                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
